---
php_repo: "ppa:ondrej/php5-5.6"

php_packages:
  - php5-common
  - php5-cli
  - php5-curl
  - php5-intl
  - php5-json
  - php5-mcrypt
  - php5-mysql
  - php5-gd
  - php5-xsl

php_config_dir: /etc/php5

php_fpm_packages:
  - php5-fpm

php_fpm_service: php5-llfpm
php_fpm_pool_file: "{{ php_config_dir }}/fpm/pool.d/www.conf"
php_fpm_ini_file: /etc/php5/fpm/php.ini
php_fpm_memory_limit: 768M
...
