---
php_repo: "ppa:ondrej/php"
php_packages:
  - php7.0-cli
  - php7.0-gd
  - php7.0-curl
  - php7.0-intl
  - php7.0-json
  - php7.0-mysql
  - php7.0-opcache
  - php7.0-readline
  - php7.0-mbstring
  - php7.0-mcrypt
  - php7.0-xsl
  - php-xdebug
  - php7.0-zip

php_config_dir: /etc/php/7.0

php_fpm_packages:
  - php-fpm

php_fpm_service: php7.0-fpm
php_fpm_pool_file: "{{ php_config_dir }}/fpm/pool.d/www.conf"
php_fpm_ini_file: /etc/php/7.0/fpm/php.ini
php_fpm_memory_limit: 768M
...
